### ISSUE TITLE
Add settings tab

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro-inspect#10]
Add a settings panel, currently wanted nobs:

* [ ] Max number of recorded transactions (currently 100)
* [ ] Max number of recorded network requests (currently 50)
* [ ] Max number of db history (currently 100)

**Comment by patrickcmserrano** [comment]
Also would like to toggle wheter the snapshot panel would start openned or not.

**Comment by wilkerlucio** [comment]
Hello @patrickcmserrano, the idea is good, its something I would like to add. About this case, in specific, I think we could just store the last state per-app. There is already some infrastructure to do that (it uses to save current watches for example). This way at least you don't have to change on every reload, for this case, this seems better IMO than having a setting for it. What do you think?

**Comment by awkay** [comment]
Closed due to inactivity.
