### ISSUE TITLE
Time Literals in chrome UI

### ISSUE THREAD

**Issue by archaic** [fulcrologic/fulcro-inspect#101]
Hi, im using Tick on the frontend and backend, works really great - but in
fulcro inspect a #time/date ["2021-11-27"] (https://github.com/henryw374/time-literals)
shows up as [TaggedValue: unknown, 2021-11-27].

I Had a quick look, would the place to modify this be in
fulcro.inspect.ui.data-viewer/render-data ?, and then again in DataViewer

**Comment by awkay** [comment]
You can install custom transit handlers in the Fulcro side, and that should clean up the look a bit.  Both Fulcro and Inspect need to know how to interpret the values, and Inspect is fine with tagged values. Adding additional stuff to inspect is ok as long as it doesn't require additional dependencies on the Fulcro client side (e.g. tick cannot be a dep for everyone).  However, the reason I didn't do this, is that any lib author can come up with any encoding for anything...and preferring some particularly library *you* like over others just doesn't make a lot of sense. Also, are you prepared to do rigorous testing of your changes, rebuild the electron apps for all platforms, etc.?  I'm not prepared to dedicate that time for this particular change unless you come with something that addresses more than just your pet library in a better way that works for Chrome and Electron equally without requiring new deps in Fulcro proper.

I'd recommend just installing the custom transit handlers as per the book.
