### ISSUE TITLE
Empty DB in fulcro inspect when refresh with devtools open

### ISSUE THREAD

**Issue by R-Larsson** [fulcrologic/fulcro-inspect#102]
Hi,

There seems to be a problem with loading the initial state into fulcro inspect when the developer tools is open.

I am following the getting started section in the fulcro book and I have followed it to "5.6.4. Step 3 — Receive the Data Feed as Props in Root" but I can't see the initial db in fulcro inspect if I refresh the page with the developer tools open. If I close developer tools and refresh the page and then open developer tools again after the page has loaded the DB is showing correctly in fulcro inspect.

I am using google chrome version 113 on NixOS 22.11.

**Comment by awkay** [comment]
Rewrite of latest release should fix this. See new issue around known bugs that I'm working on
