### ISSUE TITLE
Transaction doesn't register in transaction tab

### ISSUE THREAD

**Issue by RokLenarcic** [fulcrologic/fulcro-inspect#27]
See https://github.com/fulcrologic/fulcro/issues/118 for code.

If you follow the instructions you should get a working app.

Run the client and server and open fulcro inspect.

Click the button. You'll notice that UI changes, but no transaction shows up in transactions tab of fulcro inspect.

**Comment by wilkerlucio** [comment]
@RokLenarcic I found an issue on your transaction code:

```clojure
(prim/transact! this `[(simple-edit {:path [:person/by-id ~id :person/active] :fn ~not}) f/form-root-key])
```

That line is wrong, you are sending a symbol to transaction, which is invalid there, it's missing the unquote on the `f/form-root-key`, changing to this makes it work:

```clojure
(prim/transact! this `[(simple-edit {:path [:person/by-id ~id :person/active] :fn ~not}) ~f/form-root-key])
```
