### ISSUE TITLE
Support ClojureScript 1.10.64

### ISSUE THREAD

**Issue by pedrorgirardi** [fulcrologic/fulcro-inspect#30]
Hi,

ClojureScript 1.10.64 is no longer returning 2-element vectors for [map entries](https://github.com/mfikes/clojurescript-site/blob/1215b7c7e0f5aac0060ff6e1a762d1bed13a9315/content/news/2018-xx-yy-release.adoc#map-entries), it now returns a dedicated map entry type and that seems to be the cause of this error:

![screen shot 2018-02-27 at 9 30 21 pm](https://user-images.githubusercontent.com/585191/36764659-212d57b2-1c60-11e8-9004-cf682eb8b602.png)

**Comment by wilkerlucio** [comment]
Thanks for the report, I'll look it up some time this week.

**Comment by wilkerlucio** [comment]
@pedrorgirardi I figure it's actually an issue in Fulcro, check the related issue for more details: https://github.com/fulcrologic/fulcro/issues/160

**Comment by awkay** [comment]
Try Fulcro 2.3.1-SNAPSHOT

**Comment by pedrorgirardi** [comment]
Thanks, Wilker and Tony!
