### ISSUE TITLE
Chrome plugin icon on toolbar never "lights up"

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-inspect#39]
The plugin seems to be working for me, but at first I thought it was broken because the icon in the main toolbar is always "off", even though it has detected an app andthe menu item within it is working, as is the devtools tab itself.

**Comment by wilkerlucio** [comment]
Good point, I had done nothing regarding it. The thing is that chrome now adds an icon there, no matter if you actually used one or not. But I think is a good UI thing if we can see it there, I'll work on that before the official release.

**Comment by wilkerlucio** [comment]
Closed via 649745ddab9c7583c3182132430da2c1c97af475
