### ISSUE TITLE
Finding text in DB does not work

### ISSUE THREAD

**Issue by felipedau** [fulcrologic/fulcro-inspect#44]
I tried to search for a value using `ctrl/command` + `f` but it pops up search in the current page, not the DB. I noticed there is a `Find` field at the bottom but that doesn't work as well.

Thanks!

**Comment by awkay** [comment]
I have the same issue, and it is pretty important. I'll fix this one @wilkerlucio. I've already looked at the data viewer code, and have some ideas. I plan on adding a search field to the toolbar, and then:

- Typing in the search field will highlight any matches in the currently-expanded content
- Pressing "Recursive Search" button next to the field will cause it to fold open anything that contains matches.
