### ISSUE TITLE
Inspect interferes with progress updates in networking

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-inspect#49]
I just customized networking for file uploads, and when inspect is present it wraps the networking and causes it to mis-detect the kind of network, which in turn sends nil for the progress update function, and that keeps progress updates from reporting.

**Comment by wilkerlucio** [comment]
Can you please send an example case that fails on it?

**Comment by awkay** [comment]
Yeah, will do.

**Comment by awkay** [comment]
https://github.com/awkay/file-upload-demo

Right now I've got the development preload in shadow NOT loading inspect, and the card will work properly: When you add a file it will upload, and progress will update (use Chromes devtools to slow down your networking during upload to see the progress updates)...you can tell it worked if state of progress ends at 100.

Now add Inspect back into preloads and reload. Uploading a file will no longer get progress updates (progress will be pegged at 0).

**Comment by awkay** [comment]
Confirmed fixed.

**Comment by awkay** [comment]
OK, another one. Just notices that it also interferes with the NetworkBehavior interface for parallel loads.  The example was updated.  If you upload multiple files, they should go in parallel, but with Inspect installed they go in sequence. This is because the wrapper doesn't delegate the protocol, so it cannot sense the parallel support.

**Comment by awkay** [comment]
I see your prior commit...I'll fix it :)
