### ISSUE TITLE
Infinite loops in networking

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-inspect#52]
Got a custom remote that goes into an infinite loop with inspect. Works fine with prior versions (was using beta8 I think). It is hitting REST endpoint. Not sure why yet, but it is quite surprising and bothersome...v2.2.1

**Comment by awkay** [comment]
So, this is the 3rd time in as many weeks that Inspect's networking has caused me to spend significant time debugging what looks like an application problem.  I think we should make the networking instrumentation default to OFF and add an option that can be configured to turn it on if people want it.  I never use it, and it has cost me probably 10 hours of head scratching...the cost if *far* outweighing the benefit.

**Comment by wilkerlucio** [comment]
Would be nice to understand whats going on, sorry for the frustration, I personally use the network layer a lot and never have problems with it, but I'm not using the new things or progress handlers, so my guess is that something around it. We could add an option to disable but I think enable by default is the correct, we just need to figure out what edge case are you hitting and fix it.

**Comment by awkay** [comment]
I've spent a while trying to debug it, but I cannot remember how to run the thing properly in dev mode (be nice to have some instructions in the repo).  I did shadow watch on the chrome targets and updated the chome extension.  Think that was right...

I tried adding an option to disable network pane, but I can't figure out your code path for it...I'm getting some exception on a `reset!` when I change your network wrappers to not wrap. I think because you expect them to be wrappers somewhere else.

I don't have time to mess with it further...I suspect that the direct call to `ok-handler` on line 186 of client.cljs is wrong (it should really try the networking even if you don't choose to transform it, shouldn't it???)

I doubt that is my problem, though.

**Comment by awkay** [comment]
Ah, significant note:

This remote is doing REST, and the middleware is rewriting the request like so:

(defn wrap-smarty-streets-request
  "Middleware to convert a Fulcro mutation from this namespace into the proper REST API request. "
  [handler {:keys [auth-id]}]
  (fn [{:keys [body]}]
    (let [query-ast   (some-> body fp/query->ast1)
          valid?      (is-valid-request? query-ast)
          {[endpoint-key _] :key :keys [params]} query-ast
          website-key (if (string? auth-id) auth-id (deref auth-id))
          url         (smarty-url endpoint-key params website-key)]
      (if valid?
        {:method  :get
         :body    nil
         :headers nil
         :url     url}
        {}))))

Note that the body is nil, and really the only thing we care about is URL.

**Comment by wilkerlucio** [comment]
@awkay I'll take a look, in the meantime I had updated the docs for contribution, please let me know if still something missing there

**Comment by wilkerlucio** [comment]
@awkay is this still a valid issue?

**Comment by wilkerlucio** [comment]
Closing it for now, please re-open if still an issue.
