### ISSUE TITLE
Fulcro-inspect db view problems. E.g. stops updating db view when tempid resolution happens

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-inspect#56]
0. Open up fulcro-inspect
1. Make a Foo with tempid
2. In a mutation, resolve tempid to some real id
3. Change other details in Foo, fulcro-inspect doesn't update.
4. Close and reopen fulcro-inspect, fulcro-inspect works again

**Comment by wilkerlucio** [comment]
Hello, thanks for the report, this week I'm pretty busy but I'll try to get to it as soon as possible.

**Comment by awkay** [comment]
I've seen other issues where db tab loses track of things.

**Comment by awkay** [comment]
Perhaps as a first shot we add a "re-sync" button to get thing back in sync. Perhaps there is a way to detect we're out of sync and force a re-sync.

**Comment by awkay** [comment]
So, I've released new versions of chrome/electron with more robust db code. Perhaps this will fix problems.
