### ISSUE TITLE
SecurityError when third-party cookies and site data are blocked

### ISSUE THREAD

**Issue by MrEbbinghaus** [fulcrologic/fulcro-inspect#58]
Chrome throws a SecurityError when third-party cookies and site data are blocked, resulting in a blank Fulcro Inspect tab. 

Relevant ressource:
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by awkay** [comment]
Perhaps use the new Electron based Inspect?
