### ISSUE TITLE
Show IDs of state machine mutations in transactions tab

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-inspect#64]
This is a fulcro incubator specific thing, but perhaps it will also apply to a few fulcro things. These days, I get a lot of 
```
fulcro.incubator.ui-state-machines/trigger-state-machine-event
fulcro.incubator.pessimistic-mutations/finish-pmutation
fulcro.client.mutations/merge!
```
so the transactions tab in the fulcro inspector becomes less useful. I almost always have to scroll to the right to be able to distinguish between all these generic mutations. I think exposing IDs (somehow) would be a huge usability boost.

**Comment by awkay** [comment]
Right, that would probably be good.  It really would not be that hard to read the EDN of the transaction and covert it to a more useful form for the reader.

**Comment by awkay** [comment]
Fixed for 3
