### ISSUE TITLE
"socket.io-client" is not available

### ISSUE THREAD

**Issue by eneroth** [fulcrologic/fulcro-inspect#71]
I updated shadow-cljs (`2.8.61`) and Fulcro (`3.0.2`), and sprang upon this problem. I'm not sure if either or both are the cause of it.

`The required JS dependency "socket.io-client" is not available, it was required by "com/fulcrologic/fulcro/inspect/inspect_ws.cljs".`

So I did the old `yarn add socket.io-client`. Though the complaint is gone, Fulcro Inspect seems unsatisfied by this solution, reporting that no app is connected.

**Comment by awkay** [comment]
Thanks for trying.  So, you've got that preload in your app, you have cache disabled in the browser, and you've reloaded the app?  What OS?

**Comment by awkay** [comment]
OK.  The README does mention the socket io, and should only be a requirement if using the electon app.  The no app is connected was a bug in 3.0.2, try 3.0.2-1,

The socket-io thing is a diff accident that I'll have to patch and update the docs for.

**Comment by awkay** [comment]
The socket-io dependency issue is cleared up in 3.0.3.
