### ISSUE TITLE
Problems with expression parsing (purely cosmetic)

### ISSUE THREAD

**Issue by eneroth** [fulcrologic/fulcro-inspect#77]
It seems that the query tab sometimes has problems understanding deep levels of nesting (though I've only encountered this in writing arguments to functions).

<img width="1149" alt="Screenshot 2019-10-21 at 14 56 20" src="https://user-images.githubusercontent.com/333974/67207067-1d9e9980-f413-11e9-82b2-e0352c01fd0c.png">

To reproduce, paste the following into the editor:

```clojure 
[{(:zd/search_articles_advanced_2
   {:n_results 10
    :filter_expr {:should [{:must [{:terminal_exprs {:matches_text "Water"}}]}]}})
  [:zd.Article/article_title]}]
```

**Comment by awkay** [comment]
Hi, thanks for the report.  The query tab has a number of small issues. My standard is to only leave issues open that will be fixed within a week or two.  If you care to submit a PR, we'd be glad to have it.  See the new Fulcro video on optimization on YouTube, as it shows an easy way to develop against Inspect.

If you don't plan on submitting a PR, please close this issue.

**Comment by wilkerlucio** [comment]
I can give more context on this, it is an incomplete implementation on the side of codemirror mode, right now it doesn't support regular generic Clojure maps, the code for the codemirror mode is here: https://github.com/fulcrologic/fulcro-inspect/blob/master/src/ui/com/wsscode/oge/ui/oge-mode.js

I don't have plans to get back on it soon, but a PR adding more support would be greatly appreciated.

**Comment by eneroth** [comment]
Gotcha, thanks. I'll close this for now, I'm not sure if I can make time for a PR within the week.
