### ISSUE TITLE
DB view difficult to read in dark mode

### ISSUE THREAD

**Issue by eoliphan** [fulcrologic/fulcro-inspect#79]
Need a different palette  for DM or perhaps colors that work well in both

![Screenshot 2019-10-31 11 08 25](https://user-images.githubusercontent.com/1065736/67959326-ef694880-fbce-11e9-8891-75a6ca6faac5.png)

**Comment by awkay** [comment]
Feel free to submit a PR...this is not an issue that will be solved by Fulcrologic.
