### ISSUE TITLE
No such file or directory "~/Library/Application Support/fulcro-inspect-electron/Settings" on start

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-inspect#87]
I've never used fulcro inspect electron before, so i'm guessing at some point there was initialization code that became stale with 2.2.1.

**Comment by awkay** [comment]
Hm...did it prevent it from starting. I don't expect that file to be there...supposed to be auto-created, I thought.

**Comment by levitanong** [comment]
Yup, prevented it from starting.
![Screen Shot 2020-01-14 at 14 48 13](https://user-images.githubusercontent.com/869638/72320550-e4f22180-36dc-11ea-9f32-b4d93ff23464.png)

**Comment by awkay** [comment]
Bummer...I thought it would auto-create that file...easy fix, though.

**Comment by awkay** [comment]
Released new images that should fix it.
