### ISSUE TITLE
Data Watcher - watch a query

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro-inspect#9]
Some way to add watches that are Fulcro queries, so we can get live feedback on some specific part of the DB filtered via the given query.

**Comment by awkay** [comment]
Om Next: om.next/default-ui->props
Fulcro 2.0: fulcro.client.primitives/fulcro-ui->props

Can give you that provided a parsing env and React component

**Comment by wilkerlucio** [comment]
Thanks, for this I'm thinking a user custom query more than a query from a component, for example, if you like to watch every remote on the request history, you could write a query:

```clojure
[{:fulcro.inspect.ui.network/request-id [{* [:fulcro.inspect.ui.network/remote]}]}]
```

Then you have a dynamic view with just this section of the DB. Very much like the path watchers, but running a query against the DB (and that `*` syntax is something that this parser needs to support, but it doesn't need to be the same client parser).

**Comment by awkay** [comment]
Closed for inactivity.
