### ISSUE TITLE
add brave browser support

### ISSUE THREAD

**Issue by alidlo** [fulcrologic/fulcro-inspect#90]
Brave browser supports chrome extensions but for whatever reason the Fulcro Inspect extension is not loading my app

I downloaded the extension in Chrome too and verified that my app is indeed being loaded when using Chrome. So seems to be something specific to Brave support.  

I'll resort to using the Chrome browser for now, but wanted to report that at least for me Fulcro Inspect isn't working w Brave

**Comment by wilkerlucio** [comment]
Hello, it does work on Brave, but you have to allow cookies, not sure why, but this works: 
![Screen Shot 2020-02-15 at 19 42 25](https://user-images.githubusercontent.com/25736/74596252-5a7a4600-502b-11ea-94b2-cf7fdfa3e997.png)

**Comment by alidlo** [comment]
great, thanks 👍
