### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by hoxu** [fulcrologic/fulcro-inspect#97]
It would be nice to have a Firefox extension.

I figured it might be good to have an issue that people can vote for (:+1:) and subscribe to.

**Comment by michaelwhitford** [comment]
I use firefox for virtually everything, except fulcro development.  I would love a firefox extension, but not enough to write it myself.  Tony provides a huge value for free in these tools he created.  Do you want it enough to write it yourself?  The source code for the chrome extension is right here, dig in.  If you want help I could spend some time, just not enough to write it all myself.

**Comment by holyjak** [comment]
Hi Hoxu! Though I would like a Firefox extension myself, I am sure Tony is not going to create it. He has way toooooo much work already, and there is already a fine solution to the problem.

If anyone is going to make it, it will be somebody from the community. And such a person will do it because s/he wants it her/himself, not because there is an issue with possibly some votes.

So I think this issue is unnecessary.

**Comment by awkay** [comment]
Hi, I'm glad you're trying to help by tracking something you'd like to see.

However, I don't take requests as issues. You can participate in online discussions (in discussions tab) or in Slack about things you'd like to help with. You can fork the repo and make it yourself. it might not even be that hard. I personally see no need for it, don't want another thing to maintain/distribute, and see that there is a trivial, free, supported solution (Chrome).

I also don't leave issues open that I do not intend to work on.

I'm not a fan of seeing 1000's of issues in a repo that clearly have no meaning (or intention of being worked on), and so I close anything that will not get horsepower from me or a known collaborator. I also have a policy of closing issues that sit for more than a few weeks without progress. If the community wants it, then someone will contribute it. There's no need to track votes as if they are somehow the "pay" of the open-source world.

**Comment by carrete** [comment]
I've been quite happy with the standalone electron version which has allowed me to develop and test with Firefox and Safari. Perhaps this would be an adequate substitute?

Also, I have doubts about using votes to prioritize issues. I don't think it's worth the opportunity cost of creating every possible issue in sufficient detail this requires, nor would I expect people outside the core development team to understand every issue and be able to determine relative priority, never mind simply read every issue. I'm quite happy to let Tony et al continue to decide what they should be working on
