### ISSUE TITLE
Diff added and Diff removed show nil

### ISSUE THREAD

**Issue by markusalbertgraf** [fulcrologic/fulcro-inspect#99]
Hi,

in transactions tab when a transaction is selected 'Diff added' and 'Diff removed' keep showing nil.
This might be due to states not being automatically fetched.

**Comment by awkay** [comment]
Known issue. Yes, it is related to the fact that the two states are no longer always present (speed up was significant). Now, the diff calc should happen IF you load the before and after states.

**Comment by awkay** [comment]
Fixed in latest release
